FROM ubuntu:16.04

ADD http://www.edgeworx.io/downloads/jdk/jdk-8u211-64.tar.gz /opt
ADD 

RUN cd /opt && \
  tar xzf jdk-8u211-64.tar.gz && \
  cd /opt/jdk1.8.0_211/ && \
  update-alternatives --install /usr/bin/java java /opt/jdk1.8.0_211/bin/java 1100 && \
  rm -R jdk-8u211-64.tar.gz
