# Test arm32 build on RPi agent

trigger:
  - master

pr:
  - master

pool:
  name: 'RPi'

variables:
  repository: 'focal-freedom-236620/connector'
  type: $(Build.SourceBranchName)
  commit: $(Build.SourceVersion)

steps:
  - task: Docker@2
    displayName: 'build and push Java for arm32'
    inputs:
      containerRegistry: 'Edgeworx GCP'
      repository: $(repository)
      command: 'buildAndPush'
      Dockerfile: 'java/Dockerfile.arm32'
      tags: |
        $(commit)
        $(type)
        latest
