# Test arm32 build on RPi agent

trigger:
  - master
  - develop

pr:
  - master

pool:
  name: 'RPi'

variables:
  repository: 'focal-freedom-236620/'
  type: $(Build.SourceBranchName)
  commit: $(Build.SourceVersion)

steps:
  - task: Docker@2
    displayName: 'build and push Java for arm32'
    inputs:
      containerRegistry: 'Edgeworx GCP'
      repository: '$(repository)java'
      command: 'buildAndPush'
      Dockerfile: 'java/Dockerfile.arm32'
      buildContext: '.'
      tags: |
        $(commit)
        $(type)
        latest
        arm32
