trigger:
  - master
  - develop

jobs:
  # - job: arm32
  #   pool: RPi32
  #   steps:
  #     - template: job.yml
  #       parameters:
  #         name: web
  #         shortName: web

  # - job: arm64
  #   pool: RPi64
  #   steps:
  #     - template: job.yml
  #       parameters:
  #         name: web
  #         shortName: web

  - job: x86
    pool:
      vmImage: 'Ubuntu-16.04'
    steps:
      - template: '$(System.DefaultWorkingDirectory)/templates/build-images.yml'
        parameters:
          platform: 'x86'
