JAVA_IMAGE_VERSION=8u211
JAVA_IMAGE_NAME=java-ubuntu-$(IMAGE_ARCH)
JAVA_IMAGE_TAGNAME=$(JAVA_IMAGE_NAME):$(JAVA_IMAGE_VERSION)

NODE_IMAGE_VERSION=8.16.0
NODE_IMAGE_NAME=node-alpine-$(IMAGE_ARCH)
NODE_IMAGE_TAGNAME=$(NODE_IMAGE_NAME):$(NODE_IMAGE_VERSION)

PYTHON_IMAGE_VERSION=2.7.16
PYTHON_IMAGE_NAME=python-alpine-$(IMAGE_ARCH)
PYTHON_IMAGE_TAGNAME=$(PYTHON_IMAGE_NAME):$(PYTHON_IMAGE_VERSION)

PYTHON3_IMAGE_VERSION=3.7.3
PYTHON3_IMAGE_NAME=python-alpine-$(IMAGE_ARCH)
PYTHON3_IMAGE_TAGNAME=$(PYTHON3_IMAGE_NAME):$(PYTHON3_IMAGE_VERSION)

GO_IMAGE_VERSION=1.11.9
GO_IMAGE_NAME=golang-alpine-$(IMAGE_ARCH)
GO_IMAGE_TAGNAME=$(GO_IMAGE_NAME):$(GO_IMAGE_VERSION)

default: build

build:
	docker build -t $(JAVA_IMAGE_TAGNAME) -f java/Dockerfile.$(IMAGE_ARCH) .
	docker tag $(JAVA_IMAGE_TAGNAME) $(JAVA_IMAGE_NAME):latest

	docker build -t $(NODE_IMAGE_TAGNAME) -f nodejs/Dockerfile.$(IMAGE_ARCH) .
	docker tag $(NODE_IMAGE_TAGNAME) $(NODE_IMAGE_NAME):latest

	docker build -t $(PYTHON_IMAGE_TAGNAME) -f python/Dockerfile.$(IMAGE_ARCH) .
	docker tag $(PYTHON_IMAGE_TAGNAME) $(PYTHON_IMAGE_NAME):latest

	docker build -t $(PYTHON3_IMAGE_TAGNAME) -f python3/Dockerfile.$(IMAGE_ARCH) .
	docker tag $(PYTHON3_IMAGE_TAGNAME) $(PYTHON3_IMAGE_NAME):latest

	docker build -t $(GO_IMAGE_TAGNAME) -f golang/Dockerfile.$(IMAGE_ARCH) .
	docker tag $(GO_IMAGE_TAGNAME) $(GO_IMAGE_NAME):latest

push:build
	docker push $(JAVA_IMAGE_TAGNAME)
	docker push $(JAVA_IMAGE_NAME)

	docker push $(NODE_IMAGE_TAGNAME)
	docker push $(NODE_IMAGE_NAME):latest

	docker push $(PYTHON_IMAGE_TAGNAME)
	docker push $(PYTHON_IMAGE_NAME):latest

	docker push $(PYTHON3_IMAGE_TAGNAME)
	docker push $(PYTHON3_IMAGE_NAME):latest

	docker push $(GO_IMAGE_TAGNAME)
	docker push $(GO_IMAGE_NAME):latest
