# Default architecture
IMAGE_ARCH=x86

JAVA_IMAGE_VERSION=8u211
JAVA_IMAGE_NAME=iofog/java-ubuntu-$(IMAGE_ARCH)
JAVA_IMAGE_TAGNAME=$(JAVA_IMAGE_NAME):$(JAVA_IMAGE_VERSION)

NODE_ERBIUM_IMAGE_VERSION=12
NODE_IMAGE_NAME=iofog/node-alpine-$(IMAGE_ARCH)
NODE_IMAGE_TAGNAME=$(NODE_IMAGE_NAME):$(NODE_ERBIUM_IMAGE_VERSION)

NODE_FERMIUM_IMAGE_VERSION=14
NODE_IMAGE_NAME=iofog/node-alpine-$(IMAGE_ARCH)
NODE_IMAGE_TAGNAME=$(NODE_IMAGE_NAME):$(NODE_FERMIUM_IMAGE_VERSION)

PYTHON_IMAGE_VERSION=2.7.16
PYTHON_IMAGE_NAME=iofog/python-alpine-$(IMAGE_ARCH)
PYTHON_IMAGE_TAGNAME=$(PYTHON_IMAGE_NAME):$(PYTHON_IMAGE_VERSION)

PYTHON3_IMAGE_VERSION=3.7.3
PYTHON3_IMAGE_NAME=iofog/python-alpine-$(IMAGE_ARCH)
PYTHON3_IMAGE_TAGNAME=$(PYTHON3_IMAGE_NAME):$(PYTHON3_IMAGE_VERSION)

GO_IMAGE_VERSION=1.11.9
GO_IMAGE_NAME=iofog/golang-alpine-$(IMAGE_ARCH)
GO_IMAGE_TAGNAME=$(GO_IMAGE_NAME):$(GO_IMAGE_VERSION)

default: build

build:
	docker build -t $(JAVA_IMAGE_TAGNAME) -f java/Dockerfile.$(IMAGE_ARCH) .

	docker build -t $(NODE_IMAGE_TAGNAME) -f nodejs/node8-legacy/Dockerfile.$(IMAGE_ARCH) .
	docker build -t $(NODE_ERBIUM_IMAGE_TAGNAME) -f nodejs/node12/Dockerfile.$(IMAGE_ARCH) .
	docker build -t $(NODE_FERMIUM_IMAGE_TAGNAME) -f nodejs/node14/Dockerfile.$(IMAGE_ARCH) .

	docker build -t $(PYTHON_IMAGE_TAGNAME) -f python/Dockerfile.$(IMAGE_ARCH) .

	docker build -t $(PYTHON3_IMAGE_TAGNAME) -f python3/Dockerfile.$(IMAGE_ARCH) .

	docker build -t $(GO_IMAGE_TAGNAME) -f golang/Dockerfile.$(IMAGE_ARCH) .

push:build
	docker push $(JAVA_IMAGE_TAGNAME)

	docker push $(NODE_IMAGE_TAGNAME)
	docker push $(NODE_ERBIUM_IMAGE_TAGNAME)
	docker push $(NODE_FERMIUM_IMAGE_TAGNAME)

	docker push $(PYTHON_IMAGE_TAGNAME)

	docker push $(PYTHON3_IMAGE_TAGNAME)

	docker push $(GO_IMAGE_TAGNAME)
