FROM ubuntu:16.04

ADD ../qemu/qemu-arm-static /usr/bin/qemu-arm-static
ADD http://www.edgeworx.io/downloads/jdk/jdk-8u211-arm-32.tar.gz /opt

RUN cd /opt && \
  tar xzf jdk-8u211-arm-32.tar.gz && \
  cd /opt/jdk1.8.0_211/ && \
  update-alternatives --install /usr/bin/java java /opt/jdk1.8.0_211/bin/java 1100 && \
  rm -R /opt/jdk-8u211-arm-32.tar.gz
